/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:6e39302a-7b88-4b67-9759-4d76635857d9",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_3aJgj2Uv5",
    "aws_user_pools_web_client_id": "4de165jcbj505peug4quho0blt",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "expoimageupload29609eb383424841ac4356c85a9128aa125129-dev",
    "aws_user_files_s3_bucket_region": "sa-east-1"
};


export default awsmobile;
